ALLOWED_TOPOLOGIES = ["internet", "clos", "bcube", "xpander", "random"]
ALLOWED_VARIANTS = ["default", "online", "offline"]
MWU_FACTOR = 0.5
GAMMA = 0.5
RHO2 = 1

DEFAULT_NODE_COUNT = 10
DEFAULT_PROBABILITY = 0.5
DEFAULT_BCUBE_0_NODE_COUNT = 3
DEFAULT_LEVEL = 2
DEFAULT_MIDDLE_STAGE_COUNT = 5
DEFAULT_STAGE_COUNT = 1
DEFAULT_EDGE_SWITCH_COUNT = 5
DEFAULT_SERVERS_PER_RACK = 4
DEFAULT_LIFT_NO = 2
